<?php
session_start();
require('db1.php');   // must provide $con (mysqli)
include "con_db.php"; // keep as your system uses it

/* =========================
   ROLE CHECK (same as page)
========================= */
$role = $_SESSION['sess_userrole'] ?? '';
$queryc  = "SELECT COUNT(utype) AS c FROM user WHERE '$role' IN ('staff','mng','lab')";
$resultc = mysqli_query($con, $queryc) or die(mysqli_error($con));
$rowc    = mysqli_fetch_assoc($resultc);
$c1      = (int)($rowc['c'] ?? 0);

if (!isset($_SESSION['sess_username']) || $c1 == 0) {
    header('Location: login2?err=2');
    exit;
}

/* =========================
   INPUTS (from your link)
========================= */
$start = $_GET['stdate'] ?? '';
$end   = $_GET['endate'] ?? '';
$mode  = $_GET['mode'] ?? '';

$start = trim($start);
$end   = trim($end);
$mode  = strtoupper(trim($mode)); // OPD / IPD etc become consistent

// validate
$allowedLoc = ['OPD','OPD_DIS','OTC','IPD'];

if ($start === '' || $end === '' || $mode === '') {
    die("Missing stdate/endate/mode");
}
/*if (!in_array($mode, $allowedLoc)) {   // no strict true, safer here
    die("Invalid mode.");
}*/

/* =========================
   SAME QUERY AS YOUR REPORT
========================= */
$query = "SELECT * 
          FROM phar_sale 
          WHERE adate BETWEEN '$start' AND '$end'
            AND status!='Cancel'
            AND location IN ('$mode')
          ORDER BY adate ASC";
$result = mysqli_query($con, $query) or die(mysqli_error($con));

/* =========================
   SAME TOTAL AS YOUR REPORT
========================= */
$querydr  = "SELECT SUM(tprice) AS total_tprice
             FROM phar_sale
             WHERE adate BETWEEN '$start' AND '$end'
               AND location='$mode'
               AND status!='Cancel'";
$resultdr = mysqli_query($con, $querydr) or die(mysqli_error($con));
$data     = mysqli_fetch_assoc($resultdr);
$bill     = $data['total_tprice'] ?? 0;

/* =========================
   PDF (TCPDF)
========================= */
require_once('tcpdf/tcpdf.php'); // change if your path is different

$pdf = new TCPDF('L', 'mm', 'A4', true, 'UTF-8', false);
$pdf->SetCreator('Hospital System');
$pdf->SetAuthor('Hospital System');
$pdf->SetTitle('Datewise Sales Report');
$pdf->SetMargins(10, 12, 10);
$pdf->SetAutoPageBreak(true, 12);
$pdf->AddPage();

/* =========================
   HEADER
========================= */
$headerTitle = "Datewise Sales Report ($mode)";
$rangeText   = "From: " . date('d/m/Y', strtotime($start)) . "   To: " . date('d/m/Y', strtotime($end));
$genText     = "Generated By: " . ($_SESSION['sess_username'] ?? '') . "   |   " . date('d/m/Y h:i A');

$html = '
<h2 style="text-align:center; margin:0;">'.$headerTitle.'</h2>
<p style="text-align:center; font-size:12px; margin:4px 0 2px 0;">'.$rangeText.'</p>
<p style="text-align:center; font-size:10px; margin:0 0 10px 0;">'.$genText.'</p>

<table border="1" cellpadding="4" cellspacing="0" width="100%">
  <tr style="font-weight:bold; background-color:#f2f2f2;">
    <th width="5%"  align="center">S.No</th>
    <th width="10%" align="center">MRN</th>
    <th width="10%" align="center">Amount</th>
    <th width="10%" align="center">Date</th>
    <th width="10%" align="center">Location</th>
    
    <th width="15%" align="center">Bill By</th>
    <th width="15%" align="center">Bill No</th>
  </tr>
';

$count = 1;

while ($row = mysqli_fetch_assoc($result)) {

    $pmrn     = $row['pmrn'] ?? '';
    $amount   = $row['tprice'] ?? '';
    $adate    = $row['adate'] ?? '';
    $location = $row['location'] ?? '';
    
    $user     = $row['aby'] ?? '';
    $billno   = $row['billno'] ?? '';

    $html .= '
    <tr>
      <td align="center">'.$count.'</td>
      <td align="center">'.htmlspecialchars($pmrn).'</td>
      <td align="center">'.htmlspecialchars($amount).'</td>
      <td align="center">'.($adate ? htmlspecialchars(date('d/m/Y', strtotime($adate))) : '').'</td>
      <td align="center">'.htmlspecialchars($location).'</td>
      
      <td align="center">'.htmlspecialchars($user).'</td>
      <td align="center">'.htmlspecialchars($billno).'</td>
    </tr>
    ';

    $count++;
}

/* =========================
   TOTAL ROW
========================= */
$html .= '
  <tr style="font-weight:bold;">
    <td colspan="2" align="right">Total (SUM tprice)</td>
    <td align="center">'.htmlspecialchars($bill).'</td>
    <td colspan="6"></td>
  </tr>
</table>
';

$pdf->writeHTML($html, true, false, true, false, '');
$pdf->Output("datewise_sales_{$mode}_{$start}_to_{$end}.pdf", "I");
exit;