<?php 
    session_start();
    require('db1.php');
	$role = $_SESSION['sess_userrole'];
	
$queryc = "SELECT COUNT(utype) FROM user where '$role' in ('doctor','staff','mng','ot','endo','imo','mofficer','nurse','emergency','moopd','call','bill','billin','diet','physio','mrd','adminmng','lab','rad','gpopd','mrd')"; 
$resultc = mysqli_query($con, $queryc) or die(mysqli_error());
$rowc = mysqli_fetch_array($resultc);
$c1=$rowc['COUNT(utype)'];
	
    if(!isset($_SESSION['sess_username']) || $c1==0){
      header('Location: login2?err=2');
    }
?>


<?php

require('db1.php');

$user=$_SESSION['sess_username'];
$cyear=date('Y');
$pmrn=$_REQUEST['pmrn'];
$eid=$_REQUEST['eid'];

//$fullname = $_SESSION['sess_username'];


$query = "SELECT * FROM staff3 where sid='$user' and status='Active'"; 
	 
$result = mysqli_query($con, $query) or die(mysqli_error());

// Print out result
$row = mysqli_fetch_array($result);

$s_name=$row['sname'];



$query1 = "SELECT * FROM inpatient where pmrn='$pmrn' and eid='$eid'"; 
$result1 = mysqli_query($con, $query1) or die(mysqli_error());
$row1 = mysqli_fetch_array($result1);

$adoc=$row1['adoc'];


$query2 = "SELECT * FROM staff1 where mname='$adoc'"; 
$result2 = mysqli_query($con, $query2) or die(mysqli_error());
$row2 = mysqli_fetch_array($result2);
$a_doc_email=$row2['email'];
?>



<?php
 
require('db1.php');
$stime=date("h:i:sa");
if(isset($_POST['Submit']))
{
$pw=$_REQUEST['pw'];
$pws=$_REQUEST['pws'];


$pw1=strip_tags($pw);
if($user!=''){


$query39 = "SELECT * FROM staff3 where sid='$pws' and status='Active'"; 
$result39 = mysqli_query($con, $query39) or die(mysqli_error());
$row39 = mysqli_fetch_array($result39);





$email=array($row39['email'].','.$a_doc_email);
//$email=array('steven@sfmmkpjsh.com'.','.'diasadman16@gmail.com');
//$email='diasadman16@gmail.com';
$sname=$row39['sname'];
$apply_time=date('Y-m-d H:i:s');
	
	
$ins_query1="insert into pwl (`work`,`send_by`,`send_time`,`sent_to`,`pmrn`,`eid`) values 
('$pw','$user','$apply_time','$pws','$pmrn','$eid')";
//mysqli_query($con,$ins_query1) or die(mysql_error());

$ins_query2="insert into noti (`type`,`pmrn`,`eid`,`add_by`,`add_time`,`status`,`link`,`user`) values 
('Handover Note','$pmrn','$eid','$s_name','$apply_time','1','mo_pwl','$pws')";

if(mysqli_query($con,$ins_query1)==true and mysqli_query($con,$ins_query2)==true){

$url = "https://script.google.com/macros/s/AKfycbxJH18rXZ8JQM9Wkwrv2Ri3kNBQmYBXy9c4osrRd4IBdsJK31QG_Z9bABZcu51ubW6W/exec";
            $ch = curl_init($url);
            curl_setopt_array($ch, [
               CURLOPT_RETURNTRANSFER => true,
               CURLOPT_FOLLOWLOCATION => true,
               CURLOPT_POSTFIELDS => http_build_query([
                  "recipient" => implode(',', $email),
                  "subject"   => 'Patient Hand Over Notes',
                  "body"      => 'Hi '.$sname.', Please find below the patient Hand Over Note For Your Ready Reference -
Patient Name: '.$row1['pname'].'
Patient MRN: '.$row1['pmrn'].'

'.$pw1.'
			
Best Regards,
'.$s_name.',
Automated E-mail Generated By KPJ_IT_DHAKA'
               ])
            ]);
            $result = curl_exec($ch);
           // echo $result;
			//header("Location:test_leave");
			curl_close($ch);




	echo '<script language="javascript">';
    echo 'alert("Successfully Submitted !!"); ';
    echo '</script>';}
}





else{
	
	echo '<script language="javascript">';
    echo 'alert("You Dont Have Sufficient Leave Balance OR Replacement Name is Wrong!!"); ';
    echo '</script>';
}
}


?>

<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>Out Patient Record</title>
  
 <link rel="stylesheet" href="jsnew/normalize.min.css">   

  
      <style>

html { box-sizing: border-box; }

*, *:before, *:after {
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
}

body {
  font-family: 'Nunito',sans-serif;
  color: #384047;
  background: #A085C6;
}

form {
  max-width: 2000px;
  margin: 10px auto;
  padding: 10px 20px;
  background: #f4f7f8;
  border-radius: 8px;
  border: 1px solid #8265B0;
  box-shadow: 3px 3px 3px rgba(0,0,0,0.2)
}

h1 {
  margin: 0 0 30px 0;
  text-align: center;
}

input[type="text"],
input[type="password"],
input[type="date"],
input[type="datetime"],
input[type="email"],
input[type="number"],
input[type="search"],
input[type="tel"],
input[type="time"],
input[type="url"],
textarea,
select {
  background: rgba(255,255,255,0.1);
  border: none;
  font-size: 12px;
  height: auto;
  margin: 0;
  outline: 0;
  padding: 15px;
  width: 100%;
  background-color: #e8eeef;
  color: #8a97a0;
  box-shadow: 0 1px 0 rgba(0,0,0,0.03) inset;
  margin-bottom: 30px;
}

input[type="text1"] {
  background: rgba(255,255,255,0.1);
  border: none;
  font-size: 20px;
  font-weight:bold;
  font-color: Blue;
  height: auto;
  margin: 0;
  outline: 0;
  padding: 15px;
  width: 100%;
  background-color: yellow;
  color: Black;
  box-shadow: 0 1px 0 rgba(0,0,0,0.03) inset;
  margin-bottom: 30px;
}



input[type="radio"],
input[type="checkbox"] {
  margin: 0 4px 8px 0;
}

select {
  padding: 6px;
  height: 32px;
  border-radius: 2px;
}

button {
  padding: 19px 39px 18px 39px;
  color: #FFF;
  background-color: #A085C6;
  /*#4bc970*/
  font-size: 18px;
  text-align: center;
  font-style: normal;
  border-radius: 5px;
  width: 100%;
  border: 1px solid #8265B0;
  /*#3ac162*/
  border-width: 1px 1px 3px;
  box-shadow: 0 -1px 0 rgba(255,255,255,0.1) inset;
  margin-bottom: 10px;
}

fieldset {
  margin-bottom: 30px;
  border: none;
}

legend {
  font-size: 1.4em;
  margin-bottom: 10px;
}

label {
  display: block;
  margin-bottom: 8px;
}

label.light {
  font-weight: 300;
  display: inline;
}

.number {
  background-color: #A085C6;
  /*#5fcf80*/
  color: #fff;
  height: 30px;
  width: 30px;
  display: inline-block;
  font-size: 0.8em;
  margin-right: 4px;
  line-height: 30px;
  text-align: center;
  text-shadow: 0 1px 0 rgba(255,255,255,0.2);
  border-radius: 100%;
}

abbr[title] {
	border-bottom-width: 0;
}


@media screen and (min-width: 480px) {

  form {
    max-width: 2000px;
  }

}
      </style>

    <script src="jsnew/prefixfree.min.js"></script>



<link rel="stylesheet" href="jsnew/jquery-ui.css">
<script src="jsnew/jquery.min.js"></script>
<script src="jsnew/jquery-ui.min.js"></script>
  
  <script>
  $(document).ready(function() {
    $("#datepicker").datepicker();
  });
  </script>
  
   <script>
  $(document).ready(function() {
    $("#datepicker1").datepicker();
  });
  </script>





  <style type="text/css">
<!--
.style1 {font-weight: bold}
-->
  </style>
  
  <head>
    <title>Prescription</title>
    <link rel="stylesheet" href="jsnew/bootstrap.min.css" />  
    <script src="jsnew/jjquery.min.js"></script>
    <script src="jsnew/bootstrap.min.js"></script>

    <link href="jsnew/jquery-ui.css" rel="stylesheet" />
    <link href="./jquery.multiselect.css" rel="stylesheet" />
    <script src="jsnew/jquery-1.12.4.js"></script>
    <script src="jsnew/jquery-ui.js"></script>
    <script src="./jquery.multiselect.js"></script>


<link rel="stylesheet" href="styles.css">

   <script src="script.js"></script>
   <script src="ckeditor_new/ckeditor.js"></script>
</head>

<body>

<div id='cssmenu'>
<ul>
   <li><a href='viewnew1'><span>Home</span></a></li>
   <li class='active has-sub'><a href='#'><span>Patients</span></a>
      <ul>
         <li class='has-sub'><a href='viewnew'><span>OPD Patients</span></a>
            
         </li>
         <li class='has-sub'><a href='iview'><span>In-Patients</span></a>
            
         </li>
      </ul>
   </li>
   <li class='active has-sub'><a href='#'><span>Appointment</span></a>
      <ul>
         <li class='has-sub'><a href='cggtttt'><span>Set Doctor's Appointment</span></a>
            
         </li>
         <li class='has-sub'><a href='ami2'><span>Set Restrictions on Appointment Time</span></a>
            
         </li>
      </ul>
	  
   </li>

   <li class='last'><a href='ot'><span>OT BOOKING</span></a></li>
   <li class='active has-sub'><a href='#'><span>Reports</span></a>
      <ul>
         <li class='has-sub'><a href='view3new'><span>OPD Prescription</span></a>
            
         </li>
         <li class='has-sub'><a href='con1'><span>Outpatient Stats</span></a>
            
         </li>
		          <li class='has-sub'><a href='con2'><span>OT Stats</span></a>
            
         </li>
         <li class='has-sub'><a href='con3'><span>In-Patient Stats</span></a>
            
         </li>
		   <li class='has-sub'><a href='con11'><span>Medicine Stats</span></a>
            
         </li>

      </ul>
   </li>
   <li class='last'><a href='logout'><span>LOGOUT</span></a></li>
</ul>
</div>

<h1 align="center">Handover Notes Panel </h1>

  <!-- Stephonce R. MOrris | 2014 -->

<!-- Google Font -->
		<link href='jsnew/fonts' rel='stylesheet' type='text/css'>

<form action="" method="post" onsubmit='return confirm("Do You Want To Proceed??");' />




<form>
<table width="100%" height ="100%" border="1" align="center" bgcolor="#FFFF99" style="border-collapse:collapse;">


    <tr>
      <td colspan="1"align="center"><strong>S.No</strong></td>
      <td colspan="1"align="center"><strong>Handover Notes</strong></td>
      <td colspan="1"align="center"><strong>Notes Written By</strong></td>
      <td colspan="1"align="center"><strong>Time </strong></td>
	  <td colspan="1"align="center"><strong>Handover Given To </strong></td>
      
     

	   </tr>
  
  <tbody>
  
    <?php
	


$sel_query="Select * from pwl where pmrn= '$pmrn' and eid='$eid';";
 
$count=1;	 
$result = mysqli_query($con,$sel_query);



while($row = mysqli_fetch_assoc($result)) 
{ ?>    <tr>

      <td colspan="1" align="center"><?php echo $count; ?></td>
      <td colspan="1"align="center"><?php echo $row["work"]; ?></td>
     
	  
	  <?php
	  $rr=$row['send_by'];
	  $rr1=$row['sent_to'];
	  $send = "SELECT * FROM user where uname='$rr'"; 
	 
$send_r = mysqli_query($con, $send) or die(mysqli_error());

// Print out result
$send_row = mysqli_fetch_array($send_r);

$send1 = "SELECT * FROM user where uname='$rr1'"; 
	 
$send_r1 = mysqli_query($con, $send1) or die(mysqli_error());

// Print out result
$send_row1 = mysqli_fetch_array($send_r1);

	  
	  ?>
	   <td colspan="1"align="center"><?php echo $send_row["fullname"]; ?></td>
      <td colspan="1"align="center"><?php echo $row["send_time"]; ?> </td> 
      <td colspan="1"align="center"><?php echo $send_row1["fullname"]; ?> </td> 
	  

	  
      </tr>

	<?php $count++;  }?>

  </tbody>
</table>

</form>
</body>

</html>
