CREATE TABLE IF NOT EXISTS ot_board_status (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pname VARCHAR(150) NOT NULL,
  mrn VARCHAR(50) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'In OT',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ot_board_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  board_id INT NOT NULL,
  pname VARCHAR(150) NOT NULL,
  mrn VARCHAR(50) NOT NULL,
  old_status VARCHAR(30) NOT NULL,
  new_status VARCHAR(30) NOT NULL,
  changed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_board_id (board_id),
  INDEX idx_changed_at (changed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
